[tool.black]
target-version = ["py310"]

# Keep this default because xml/report do not know to use load it from config file:
# data_file = ".coverage"
# [tool.coverage.paths]
# source = ["plugins", "extensions"]

# [tool.coverage.report]
# exclude_also = ["pragma: no cover", "if TYPE_CHECKING:"]
# omit = ["test/*"]
# # Increase it just so it would pass on any single-python run
# fail_under = 92
# skip_covered = true
# skip_empty = true
# # During development we might remove code (files) with coverage data, and we dont want to fail:
# ignore_errors = true
# show_missing = true

# [tool.coverage.run]
# source = ["src"]
# # Do not use branch until bug is fixes:
# # https://github.com/nedbat/coveragepy/issues/605
# # branch = true
# parallel = true
# concurrency = ["multiprocessing", "thread"]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.9"
color_output = true
error_summary = true

# TODO: Remove temporary skips and close https://github.com/ansible/event-driven-ansible/issues/258
# strict = true
# disallow_untyped_calls = true
# disallow_untyped_defs = true
# disallow_any_generics = true
# disallow_any_unimported = True
# warn_redundant_casts = True
# warn_return_any = True
# warn_unused_configs = True

# site-packages is here to help vscode mypy integration getting confused
exclude = "(build|dist|site-packages|~/.pyenv|plugins/modules)"
# https://github.com/python/mypy/issues/12664
incremental = false
namespace_packages = true
explicit_package_bases = true

[tool.pylint.MASTER]
# Temporary ignore until we are able to address issues on these:
ignore-paths = "^(tests/|plugins/modules).*$"

[tool.pylint."MESSAGES CONTROL"]
disable = [
  "duplicate-code",
  "pointless-string-statement",
  "too-few-public-methods",
  "too-many-instance-attributes",
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "too-many-arguments",
  "too-many-branches",
  "inconsistent-return-statements",
  "invalid-name",
]
max-line-length=120

[tool.ruff.lint]
ignore = [ "E402" ]
