# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DeviceSummaryStatusType(str, Enum):
    """
    DeviceSummaryStatusType
    """

    """
    allowed enum values
    """
    ONLINE = 'Online'
    DEGRADED = 'Degraded'
    ERROR = 'Error'
    REBOOTING = 'Rebooting'
    POWEREDOFF = 'PoweredOff'
    UNKNOWN = 'Unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeviceSummaryStatusType from a JSON string"""
        return cls(json.loads(json_str))


