# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from ansible_collections.flightctl.edge.plugins.module_utils.api_client.models.cpu_resource_monitor_spec import CPUResourceMonitorSpec
from ansible_collections.flightctl.edge.plugins.module_utils.api_client.models.disk_resource_monitor_spec import DiskResourceMonitorSpec
from ansible_collections.flightctl.edge.plugins.module_utils.api_client.models.memory_resource_monitor_spec import MemoryResourceMonitorSpec
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

RESOURCEMONITOR_ONE_OF_SCHEMAS = ["CPUResourceMonitorSpec", "DiskResourceMonitorSpec", "MemoryResourceMonitorSpec"]

class ResourceMonitor(BaseModel):
    """
    ResourceMonitor
    """
    # data type: CPUResourceMonitorSpec
    oneof_schema_1_validator: Optional[CPUResourceMonitorSpec] = None
    # data type: MemoryResourceMonitorSpec
    oneof_schema_2_validator: Optional[MemoryResourceMonitorSpec] = None
    # data type: DiskResourceMonitorSpec
    oneof_schema_3_validator: Optional[DiskResourceMonitorSpec] = None
    actual_instance: Optional[Union[CPUResourceMonitorSpec, DiskResourceMonitorSpec, MemoryResourceMonitorSpec]] = None
    one_of_schemas: Set[str] = { "CPUResourceMonitorSpec", "DiskResourceMonitorSpec", "MemoryResourceMonitorSpec" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ResourceMonitor.model_construct()
        error_messages = []
        match = 0
        # validate data type: CPUResourceMonitorSpec
        if not isinstance(v, CPUResourceMonitorSpec):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CPUResourceMonitorSpec`")
        else:
            match += 1
        # validate data type: MemoryResourceMonitorSpec
        if not isinstance(v, MemoryResourceMonitorSpec):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MemoryResourceMonitorSpec`")
        else:
            match += 1
        # validate data type: DiskResourceMonitorSpec
        if not isinstance(v, DiskResourceMonitorSpec):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DiskResourceMonitorSpec`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ResourceMonitor with oneOf schemas: CPUResourceMonitorSpec, DiskResourceMonitorSpec, MemoryResourceMonitorSpec. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ResourceMonitor with oneOf schemas: CPUResourceMonitorSpec, DiskResourceMonitorSpec, MemoryResourceMonitorSpec. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into CPUResourceMonitorSpec
        try:
            instance.actual_instance = CPUResourceMonitorSpec.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MemoryResourceMonitorSpec
        try:
            instance.actual_instance = MemoryResourceMonitorSpec.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiskResourceMonitorSpec
        try:
            instance.actual_instance = DiskResourceMonitorSpec.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ResourceMonitor with oneOf schemas: CPUResourceMonitorSpec, DiskResourceMonitorSpec, MemoryResourceMonitorSpec. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ResourceMonitor with oneOf schemas: CPUResourceMonitorSpec, DiskResourceMonitorSpec, MemoryResourceMonitorSpec. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CPUResourceMonitorSpec, DiskResourceMonitorSpec, MemoryResourceMonitorSpec]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


