# coding: utf-8

"""
    Open Device Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: undefined
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DevicesSummary(BaseModel):
    """
    A summary of the devices in the fleet returned when fetching a single Fleet.
    """ # noqa: E501
    total: StrictInt = Field(description="The total number of devices in the fleet.")
    application_status: Optional[Dict[str, StrictInt]] = Field(default=None, description="A breakdown of the devices in the fleet by \"application\" status.", alias="applicationStatus")
    summary_status: Optional[Dict[str, StrictInt]] = Field(default=None, description="A breakdown of the devices in the fleet by \"summary\" status.", alias="summaryStatus")
    update_status: Optional[Dict[str, StrictInt]] = Field(default=None, description="A breakdown of the devices in the fleet by \"updated\" status.", alias="updateStatus")
    __properties: ClassVar[List[str]] = ["total", "applicationStatus", "summaryStatus", "updateStatus"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DevicesSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DevicesSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total": obj.get("total"),
            "applicationStatus": obj.get("applicationStatus"),
            "summaryStatus": obj.get("summaryStatus"),
            "updateStatus": obj.get("updateStatus")
        })
        return _obj


